// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace souyue {
namespace recmd {
namespace service {

namespace {


}  // namespace


void protobuf_AssignDesc_service_2eproto() {
  protobuf_AddDesc_service_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "service.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_service_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_service_2eproto() {
}

void protobuf_AddDesc_service_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::souyue::recmd::protobuf_AddDesc_message_2eproto();
  ::souyue::recmd::protobuf_AddDesc_supplement_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rservice.proto\022\024souyue.recmd.service\032\rm"
    "essage.proto\032\020supplement.proto2\317\002\n\021Conte"
    "ntBasedModel\022E\n\rqueryCategory\022\023.souyue.r"
    "ecmd.Empty\032\035.souyue.recmd.RepeatedKeyPai"
    "r\"\000\022Q\n\024predictUserInterests\022\026.souyue.rec"
    "md.Category\032\037.souyue.recmd.AlgorithmCate"
    "gory\"\000\022L\n\017queryNewsTrends\022\023.souyue.recmd"
    ".Empty\032\".souyue.recmd.CategoryDistributi"
    "on\"\000\022R\n\022queryUserInterests\022\026.souyue.recm"
    "d.Category\032\".souyue.recmd.CategoryDistri"
    "bution\"\000b\006proto3", 416);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "service.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_service_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_service_2eproto {
  StaticDescriptorInitializer_service_2eproto() {
    protobuf_AddDesc_service_2eproto();
  }
} static_descriptor_initializer_service_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace service
}  // namespace recmd
}  // namespace souyue

// @@protoc_insertion_point(global_scope)
