// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "service.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace module {
namespace protocol {

namespace {


}  // namespace


void protobuf_AssignDesc_service_2eproto() {
  protobuf_AddDesc_service_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "service.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_service_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_service_2eproto() {
}

void protobuf_AddDesc_service_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::module::protocol::protobuf_AddDesc_message_2eproto();
  ::module::protocol::protobuf_AddDesc_supplement_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rservice.proto\022\017module.protocol\032\rmessag"
    "e.proto\032\020supplement.proto2\373\004\n\021ContentBas"
    "edModel\022K\n\rqueryCategory\022\026.module.protoc"
    "ol.Empty\032 .module.protocol.RepeatedKeyPa"
    "ir\"\000\022W\n\024marshalUserInterests\022\031.module.pr"
    "otocol.Category\032\".module.protocol.Algori"
    "thmCategory\"\000\022Z\n\024predictUserInterests\022\031."
    "module.protocol.Category\032%.module.protoc"
    "ol.CategoryDistribution\"\000\022R\n\017queryNewsTr"
    "ends\022\026.module.protocol.Empty\032%.module.pr"
    "otocol.CategoryDistribution\"\000\022U\n\022queryCu"
    "rrentTrends\022\026.module.protocol.Empty\032%.mo"
    "dule.protocol.CategoryDistribution\"\000\022X\n\022"
    "queryUserInterests\022\031.module.protocol.Cat"
    "egory\032%.module.protocol.CategoryDistribu"
    "tion\"\000\022_\n\031queryUserCurrentInterests\022\031.mo"
    "dule.protocol.Category\032%.module.protocol"
    ".CategoryDistribution\"\000b\006proto3", 711);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "service.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_service_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_service_2eproto {
  StaticDescriptorInitializer_service_2eproto() {
    protobuf_AddDesc_service_2eproto();
  }
} static_descriptor_initializer_service_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace protocol
}  // namespace module

// @@protoc_insertion_point(global_scope)
